jobs:
  build:
    runs-on: ubuntu-22.04  # 指定为 Ubuntu 22.04 提高稳定性

    steps:
      - name: 检出 OpenWrt 源码（24.10）
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10  # 使用 OpenWrt 24.10
          path: openwrt

      - name: 安装 OpenWrt 编译依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git

      - name: 更新和安装 OpenWrt Feeds
        run: |
          cd openwrt
          echo "src-git custom https://github.com/shenxingyu1383/openwrt-packages" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 设置目标平台为 x86_64
        run: |
          cd openwrt
          echo "CONFIG_TARGET_x86_64=y" >> .config  # 指定目标平台为 x86_64
          make defconfig  # 生成新的配置

      - name: 安装 luci-app-wolplus 编译依赖
        run: |
          cd openwrt
          echo "CONFIG_PACKAGE_luci-base=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-core=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-firewall=y" >> .config

      - name: 选择 luci-app-wolplus 进行编译
        run: |
          cd openwrt
          echo "CONFIG_PACKAGE_luci-app-wolplus=m" >> .config
          make defconfig

      - name: 编译 luci-app-wolplus（详细日志）
        run: |
          cd openwrt
          make package/luci-app-wolplus/compile V=s -j$(nproc)

      - name: 检查编译日志（输出所有日志）
        run: |
          cd openwrt
          tail -n 1000 build_dir/target-*/logs/*  # 输出最新1000行日志，方便查看错误

      - name: 打包编译产物
        run: |
          mkdir -p output
          find openwrt/bin/packages/ -name "*.ipk" -exec cp {} output/ \;

      - name: 创建 GitHub Release 并上传 `.ipk` 文件
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: Latest Build
          draft: false
          prerelease: false
          files: output/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
