name: Build luci-app-wolplus for OpenWrt 24.10
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk unzip python3
    - name: Clone OpenWrt 24.10 source and build SDK
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v24.10.0
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "CONFIG_TARGET_x86=y" >> .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        make defconfig
        make sdk -j$(nproc)
        mv bin/targets/x86/64/openwrt-sdk-24.10.0-x86-64_*.tar.xz ../sdk.tar.xz
    - name: Extract SDK and build luci-app-wolplus
      run: |
        tar -xvf sdk.tar.xz
        mv openwrt-sdk-24.10.0-x86-64_* sdk
        cp -r luci-app-wolplus sdk/package/
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make package/luci-app-wolplus/compile V=s
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-wolplus
        path: sdk/bin/packages/x86_64/base/luci-app-wolplus_*.ipk
