name: Build luci-app-wolplus (OpenWrt 24.10)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # 指定为 Ubuntu 22.04 提高稳定性

    steps:
      - name: 检出 OpenWrt 源码（24.10）
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10  # 使用 OpenWrt 24.10
          path: openwrt

      - name: 更新和安装 OpenWrt Feeds
        run: |
          cd openwrt
          echo "src-git custom https://github.com/shenxingyu1383/openwrt-packages"
