name: Build luci-app-wolplus (OpenWrt 24.10)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出 OpenWrt 源码（24.10）
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10  # 使用 OpenWrt 24.10
          path: openwrt

      - name: 更新和安装 OpenWrt Feeds
        run: |
          cd openwrt
          echo "src-git custom https://github.com/shenxingyu1383/openwrt-packages" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 选择 luci-app-wolplus 进行编译
        run: |
          cd openwrt
          make defconfig
          echo "CONFIG_PACKAGE_luci-app-wolplus=m" >> .config
          make defconfig

      - name: 编译 luci-app-wolplus
        run: |
          cd openwrt
          make package/luci-app-wolplus/compile V=s -j$(nproc)

      - name: 打包编译产物
        run: |
          mkdir -p output
          find openwrt/bin/packages/ -name "*.ipk" -exec cp {} output/ \;

      - name: 上传 `.ipk` 文件
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-wolplus
          path: output/*.ipk
