name: Build luci-app-wolplus for OpenWrt 24.10
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 检出你的仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装完整依赖
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk unzip python3 gcc make flex bison g++ libssl-dev
        echo "Dependencies installed successfully"

    # 克隆 OpenWrt 24.10 源码并构建 SDK
    - name: Clone OpenWrt 24.10 source and build SDK
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v24.10.0
        ./scripts/feeds update -a || { echo "Feeds update failed"; exit 1; }
        ./scripts/feeds install -a || { echo "Feeds install failed"; exit 1; }
        echo "CONFIG_TARGET_x86=y" >> .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        make defconfig || { echo "Defconfig failed"; exit 1; }
        # 使用单线程并启用详细日志
        make sdk -j1 V=s || { echo "SDK build failed, check logs above"; exit 1; }
        ls -lh bin/targets/x86/64/ || { echo "SDK file not found"; exit 1; }
        mv bin/targets/x86/64/openwrt-sdk-24.10.0-x86-64_*.tar.xz ../sdk.tar.xz
        echo "SDK built and moved successfully"

    # 解压 SDK 并编译 luci-app-wolplus
    - name: Extract SDK and build luci-app-wolplus
      run: |
        tar -xvf sdk.tar.xz || { echo "SDK extraction failed"; exit 1; }
        mv openwrt-sdk-24.10.0-x86-64_* sdk
        ls -lh sdk || { echo "SDK directory not found"; exit 1; }
        cp -r luci-app-wolplus sdk/package/ || { echo "Copy luci-app-wolplus failed"; exit 1; }
        cd sdk
        ./scripts/feeds update -a || { echo "SDK feeds update failed"; exit 1; }
        ./scripts/feeds install -a || { echo "SDK feeds install failed"; exit 1; }
        make package/luci-app-wolplus/compile V=s || { echo "Compilation failed"; exit 1; }
        ls -lh bin/packages/x86_64/base/ || { echo "Compiled .ipk not found"; exit 1; }
        echo "luci-app-wolplus compiled successfully"

    # 上传编译结果
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-wolplus
        path: sdk/bin/packages/x86_64/base/luci-app-wolplus_*.ipk
      continue-on-error: true

    # 备用输出
    - name: Backup output (if upload fails)
      if: failure()
      run: |
        cd sdk/bin/packages/x86_64/base/ || { echo "No package directory, skipping backup"; exit 0; }
        tar -czf luci-app-wolplus.tar.gz luci-app-wolplus_*.ipk || { echo "Tar failed"; exit 1; }
        base64 luci-app-wolplus.tar.gz > output.txt || { echo "Base64 encoding failed"; exit 1; }
        cat output.txt
        echo "Backup output generated in logs"
